In [387]:
import pandas as pd

df =pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]] , columns = ["A","B","C"], index = ["X","Y","Z"])
df.head()

   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [388]:
df

   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [389]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, X to Z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [390]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [391]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [392]:
df['A'].unique()

array([1, 4, 7])

In [393]:
df.shape

(3, 3)

In [394]:
df.size

9

In [395]:
coffee = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv')
bios = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv')
nocs = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/noc_regions.csv')
results = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/results.csv')

In [396]:
coffee.head(10)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

In [397]:
coffee.tail(5)

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [398]:
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [399]:
coffee.sample(3)

         Day Coffee Type  Units Sold
7   Thursday       Latte          30
0     Monday    Espresso          25
12    Sunday    Espresso          45

In [400]:
# loc - loc[row, column]
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [401]:
coffee.loc[[0,1,2,7]]

        Day Coffee Type  Units Sold
0    Monday    Espresso          25
1    Monday       Latte          15
2   Tuesday    Espresso          30
7  Thursday       Latte          30

In [402]:
coffee.loc[0:3]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

In [403]:
coffee.loc[4:6 ,"Day"]

4    Wednesday
5    Wednesday
6     Thursday
Name: Day, dtype: object

In [404]:
coffee.loc[4:6 ,["Day","Units Sold"]]

         Day  Units Sold
4  Wednesday          35
5  Wednesday          25
6   Thursday          40

In [405]:
# iloc for index of column
coffee.iloc[4:6 ,[0,2]]

         Day  Units Sold
4  Wednesday          35
5  Wednesday          25

In [406]:
coffee.loc[1,"Units Sold"] = 10

In [407]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [408]:
coffee.sort_values("Units Sold", ascending=False)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [409]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=False)

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
2     Tuesday    Espresso          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20
1      Monday       Latte          10

In [410]:
for index, row in coffee.iterrows():
  print(index)
  print(row)
  print("\n\n\n")

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object




1
Day            Monday
Coffee Type     Latte
Units Sold         10
Name: 1, dtype: object




2
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object




3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object




4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object




5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object




6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object




7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object




8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object




9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object




10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object




11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object




12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object




13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object

In [411]:
coffee_new = coffee
coffee_new['price'] = 4.99
coffee_new

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   4.99
1      Monday       Latte          10   4.99
2     Tuesday    Espresso          30   4.99
3     Tuesday       Latte          20   4.99
4   Wednesday    Espresso          35   4.99
5   Wednesday       Latte          25   4.99
6    Thursday    Espresso          40   4.99
7    Thursday       Latte          30   4.99
8      Friday    Espresso          45   4.99
9      Friday       Latte          35   4.99
10   Saturday    Espresso          45   4.99
11   Saturday       Latte          35   4.99
12     Sunday    Espresso          45   4.99
13     Sunday       Latte          35   4.99

In [412]:
import numpy as np

coffee['new_price'] = np.where(coffee['Coffee Type'] == 'Espresso', 3.99 , 5.99)
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          10   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [413]:
coffee.drop(columns = ['price'], inplace = True)
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          10       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [414]:
coffee= coffee[['Day','Coffee Type','Units Sold','new_price']]
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']
coffee

          Day Coffee Type  Units Sold  new_price  revenue
0      Monday    Espresso          25       3.99    99.75
1      Monday       Latte          10       5.99    59.90
2     Tuesday    Espresso          30       3.99   119.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          35       3.99   139.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       3.99   159.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       3.99   179.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       3.99   179.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       3.99   179.55
13     Sunday       Latte          35       5.99   209.65

In [415]:
coffee = coffee.rename(columns={'new_price':'price'})
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   3.99    99.75
1      Monday       Latte          10   5.99    59.90
2     Tuesday    Espresso          30   3.99   119.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   3.99   139.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   3.99   159.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   3.99   179.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   3.99   179.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   3.99   179.55
13     Sunday       Latte          35   5.99   209.65

In [416]:
coffee.loc[[2,3],'Units Sold'] = np.nan
coffee

# coffee.dropna()
# this for drop nan rows which is 2 and 3.

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        25.0   3.99    99.75
1      Monday       Latte        10.0   5.99    59.90
2     Tuesday    Espresso         NaN   3.99   119.70
3     Tuesday       Latte         NaN   5.99   119.80
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [417]:
coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Day          14 non-null     object
 1   Coffee Type  14 non-null     object
 2   Units Sold   12 non-null     float64
 3   price        14 non-null     float64
 4   revenue      14 non-null     float64
dtypes: float64(3), object(2)
memory usage: 692.0+ bytes

In [418]:
coffee[coffee['Units Sold'].isna()]

       Day Coffee Type  Units Sold  price  revenue
2  Tuesday    Espresso         NaN   3.99    119.7
3  Tuesday       Latte         NaN   5.99    119.8

In [419]:
coffee[coffee['Units Sold'].notna()]

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso        25.0   3.99    99.75
1      Monday       Latte        10.0   5.99    59.90
4   Wednesday    Espresso        35.0   3.99   139.65
5   Wednesday       Latte        25.0   5.99   149.75
6    Thursday    Espresso        40.0   3.99   159.60
7    Thursday       Latte        30.0   5.99   179.70
8      Friday    Espresso        45.0   3.99   179.55
9      Friday       Latte        35.0   5.99   209.65
10   Saturday    Espresso        45.0   3.99   179.55
11   Saturday       Latte        35.0   5.99   209.65
12     Sunday    Espresso        45.0   3.99   179.55
13     Sunday       Latte        35.0   5.99   209.65

In [420]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
price          0
revenue        0
dtype: int64

In [421]:
coffee['Units Sold'] = coffee['Units Sold'].interpolate()
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso   25.000000   3.99    99.75
1      Monday       Latte   10.000000   5.99    59.90
2     Tuesday    Espresso   18.333333   3.99   119.70
3     Tuesday       Latte   26.666667   5.99   119.80
4   Wednesday    Espresso   35.000000   3.99   139.65
5   Wednesday       Latte   25.000000   5.99   149.75
6    Thursday    Espresso   40.000000   3.99   159.60
7    Thursday       Latte   30.000000   5.99   179.70
8      Friday    Espresso   45.000000   3.99   179.55
9      Friday       Latte   35.000000   5.99   209.65
10   Saturday    Espresso   45.000000   3.99   179.55
11   Saturday       Latte   35.000000   5.99   209.65
12     Sunday    Espresso   45.000000   3.99   179.55
13     Sunday       Latte   35.000000   5.99   209.65

In [422]:
coffee.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    253.333333
Latte       196.666667
Name: Units Sold, dtype: float64

In [423]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    36.190476
Latte       28.095238
Name: Units Sold, dtype: float64

In [424]:
coffee.groupby(['Coffee Type']).agg({'Units Sold': 'sum', 'price':'mean'})

             Units Sold  price
Coffee Type
Espresso     253.333333   3.99
Latte        196.666667   5.99

In [425]:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'price':'mean'})

                       Units Sold  price
Coffee Type Day
Espresso    Friday      45.000000   3.99
            Monday      25.000000   3.99
            Saturday    45.000000   3.99
            Sunday      45.000000   3.99
            Thursday    40.000000   3.99
            Tuesday     18.333333   3.99
            Wednesday   35.000000   3.99
Latte       Friday      35.000000   5.99
            Monday      10.000000   5.99
            Saturday    35.000000   5.99
            Sunday      35.000000   5.99
            Thursday    30.000000   5.99
            Tuesday     26.666667   5.99
            Wednesday   25.000000   5.99

In [426]:
pivot = coffee.pivot(columns = 'Coffee Type', index = 'Day', values = 'revenue')
pivot

Coffee Type  Espresso   Latte
Day
Friday         179.55  209.65
Monday          99.75   59.90
Saturday       179.55  209.65
Sunday         179.55  209.65
Thursday       159.60  179.70
Tuesday        119.70  119.80
Wednesday      139.65  149.75

In [427]:
pivot.loc['Monday','Latte']

np.float64(59.900000000000006)

In [428]:
pivot.sum()

Coffee Type
Espresso    1057.35
Latte       1138.10
dtype: float64

In [429]:
pivot.sum(axis=1)

Day
Friday       389.20
Monday       159.65
Saturday     389.20
Sunday       389.20
Thursday     339.30
Tuesday      239.50
Wednesday    289.40
dtype: float64

In [430]:
coffee['yesterday_revenue'] = coffee['revenue'].shift(2)
coffee

          Day Coffee Type  Units Sold  price  revenue  yesterday_revenue
0      Monday    Espresso   25.000000   3.99    99.75                NaN
1      Monday       Latte   10.000000   5.99    59.90                NaN
2     Tuesday    Espresso   18.333333   3.99   119.70              99.75
3     Tuesday       Latte   26.666667   5.99   119.80              59.90
4   Wednesday    Espresso   35.000000   3.99   139.65             119.70
5   Wednesday       Latte   25.000000   5.99   149.75             119.80
6    Thursday    Espresso   40.000000   3.99   159.60             139.65
7    Thursday       Latte   30.000000   5.99   179.70             149.75
8      Friday    Espresso   45.000000   3.99   179.55             159.60
9      Friday       Latte   35.000000   5.99   209.65             179.70
10   Saturday    Espresso   45.000000   3.99   179.55             179.55
11   Saturday       Latte   35.000000   5.99   209.65             209.65
12     Sunday    Espresso   45.000000   3.99   179.55             179.55
13     Sunday       Latte   35.000000   5.99   209.65             209.65

In [431]:
coffee['pct_change'] = coffee['revenue'] / coffee['yesterday_revenue']*100
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,25.000000,3.99,99.75,NaN,NaN
1,Monday,Latte,10.000000,5.99,59.90,NaN,NaN
2,Tuesday,Espresso,18.333333,3.99,119.70,99.75,120.000000
3,Tuesday,Latte,26.666667,5.99,119.80,59.90,200.000000
4,Wednesday,Espresso,35.000000,3.99,139.65,119.70,116.666667
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000
6,Thursday,Espresso,40.000000,3.99,159.60,139.65,114.285714
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000
8,Friday,Espresso,45.000000,3.99,179.55,159.60,112.500000
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667
10,Saturday,Espresso,45.000000,3.99,179.55,179.55,100.000000
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000
12,Sunday,Espresso,45.000000,3.99,179.55,179.55,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000

In [432]:
coffee['cumulative_revenue'] = coffee['revenue'].cumsum()
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue
0,Monday,Espresso,25.000000,3.99,99.75,NaN,NaN,99.75
1,Monday,Latte,10.000000,5.99,59.90,NaN,NaN,159.65
2,Tuesday,Espresso,18.333333,3.99,119.70,99.75,120.000000,279.35
3,Tuesday,Latte,26.666667,5.99,119.80,59.90,200.000000,399.15
4,Wednesday,Espresso,35.000000,3.99,139.65,119.70,116.666667,538.80
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,688.55
6,Thursday,Espresso,40.000000,3.99,159.60,139.65,114.285714,848.15
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1027.85
8,Friday,Espresso,45.000000,3.99,179.55,159.60,112.500000,1207.40
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1417.05
10,Saturday,Espresso,45.000000,3.99,179.55,179.55,100.000000,1596.60
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1806.25
12,Sunday,Espresso,45.000000,3.99,179.55,179.55,100.000000,1985.80
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2195.45

In [433]:
latte = coffee[coffee['Coffee Type']=="Latte"].copy()
latte['3day'] = latte['Units Sold'].rolling(3).sum()
latte

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue,3day
1,Monday,Latte,10.000000,5.99,59.90,NaN,NaN,159.65,NaN
3,Tuesday,Latte,26.666667,5.99,119.80,59.90,200.000000,399.15,NaN
5,Wednesday,Latte,25.000000,5.99,149.75,119.80,125.000000,688.55,61.666667
7,Thursday,Latte,30.000000,5.99,179.70,149.75,120.000000,1027.85,81.666667
9,Friday,Latte,35.000000,5.99,209.65,179.70,116.666667,1417.05,90.000000
11,Saturday,Latte,35.000000,5.99,209.65,209.65,100.000000,1806.25,100.000000
13,Sunday,Latte,35.000000,5.99,209.65,209.65,100.000000,2195.45,105.000000

In [434]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [435]:
bios.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [436]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [437]:
bios.loc[bios['height_cm'] > 215]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5089,5108,Viktor Pankrashkin,1957-06-19,Moskva (Moscow),Moskva,RUS,Soviet Union,220.0,112.0,1993-07-24
5583,5606,Paulinho Villas Boas,1963-01-26,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN
5716,5739,Uwe Blab,1962-03-26,München (Munich),Bayern,GER,Germany West Germany,218.0,110.0,NaN
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
5796,5819,Andy Campbell,1956-07-21,Melbourne,Victoria,AUS,Australia,218.0,93.0,NaN
6223,6250,Lars Hansen,1954-09-27,København (Copenhagen),Hovedstaden,DEN,Canada,216.0,105.0,NaN
6270,6298,Hu Zhangbao,1963-04-05,NaN,NaN,NaN,People's Republic of China,216.0,135.0,NaN
6409,6440,Sergey Kovalenko,1947-08-11,NaN,NaN,NaN,Soviet Union,216.0,111.0,2004-11-18
6420,6451,Jānis Krūmiņš,1930-01-30,Cēsis,Cēsu novads,LAT,Soviet Union,218.0,141.0,1994-11-20
6504,6537,Luc Longley,1969-01-19,Melbourne,Victoria,AUS,Australia,220.0,135.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN
7074,7111,Paulo da Silva,1963-07-21,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
7188,7226,Vladimir Tkachenko,1957-09-20,Golovinka,Krasnodar Kray,RUS,Soviet Union,220.0,110.0,NaN
7281,7320,Stojko Vranković,1964-01-22,Drniš,Šibensko-kninska županija,CRO,Croatia Yugoslavia,217.0,115.0,NaN
7376,7416,Eurelijus Žukauskas,1973-08-22,Klaipėda,Klaipėda,LTU,Lithuania,218.0,115.0,NaN
52608,52983,Aleksey Kazakov,1976-03-18,Naberezhnye Chelny,Respublika Tatarstan,RUS,Russian Federation,217.0,102.0,NaN
82100,82753,Frédéric Weis,1977-06-22,Thionville,Moselle,FRA,France,218.0,110.0,NaN
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN
107408,108533,Peter John Ramos,1985-05-23,Fajardo,Puerto Rico,PUR,Puerto Rico,219.0,113.0,NaN
112312,113568,Stanko Barać,1986-08-13,Mostar,Hercegovačko-neretvanski kanton,BIH,Croatia,217.0,110.0,NaN
112332,113588,Andreas Glyniadakis,1981-08-26,Chania,Kriti,GRE,Greece,216.0,115.0,NaN
112337,113593,Hamed Haddadi,1985-05-19,Ahvaz,Khuzestan,IRI,Islamic Republic of Iran,218.0,110.0,NaN
118663,120400,Timofey Mozgov,1986-07-16,NaN,NaN,NaN,Russian Federation,216.0,113.0,NaN
118676,120415,Dmitry Musersky,1988-10-29,Makiïvka,Donetsk,UKR,Russian Federation,219.0,104.0,NaN
120266,122147,Zhang Zhaoxu,1987-11-18,Binzhou,Shandong,CHN,People's Republic of China,221.0,110.0,NaN
121694,123709,Salah Mejri,1986-06-15,Jendouba,Jendouba,TUN,Tunisia,216.0,110.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN
130460,133147,Li Muhao,1992-06-02,Guiyang,Guizhou,CHN,People's Republic of China,218.0,115.0,NaN
130461,133148,Zhou Qi,1996-01-16,Xinxiang,Henan,CHN,People's Republic of China,217.0,95.0,NaN
138671,142084,Ondřej Balvín,1992-09-20,Ústí nad Labem,Ústecký kraj,CZE,Czechia,216.0,107.0,NaN
139365,142836,Moustapha Fall,1992-02-23,Paris,Paris,FRA,France,218.0,NaN,NaN

In [438]:
bios.loc[bios['height_cm'] > 215, ['name', 'height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [439]:
bios[bios['height_cm'] > 215][['name', 'height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [440]:
bios[(bios['height_cm'] > 215) & (bios['born_country'] == 'USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [441]:
bios[bios['name'].str.contains('Keith')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [442]:
#find athletes born in cities that start with vowel
vowel_cities = bios[bios['born_city'].str.contains(r'^[AEIOUaeiou]', na = False)]
print(vowel_cities)

        athlete_id                     name   born_date       born_city  \
5                6        Nicolas Chatelain  1970-01-13          Amiens
10              11  Élie, Comte de Lastours  1874-08-12         Orgeval
17              18     Jean-Philippe Gatien  1968-10-16            Alès
35              36          Étienne Thobois  1967-09-20          Amiens
40              41           Julie Bradbury  1967-02-12          Oxford
...            ...                      ...         ...             ...
145395      149118             Abbey Murphy  2002-04-14  Evergreen Park
145398      149121          Grace Zumwinkle  1999-04-23       Excelsior
145405      149128             Brian Cooper  1993-11-01       Anchorage
145418      149141              Nick Perbix  1998-06-15       Elk River
145427      149150            Jared Shumate  1999-03-06         Atlanta

       born_region born_country            NOC  height_cm  weight_kg  \
5            Somme          FRA         France      181.0       70.0
10        Yvelines          FRA         France        NaN        NaN
17            Gard          FRA         France      178.0       73.0
35           Somme          FRA         France      186.0       78.0
40         England          GBR  Great Britain      175.0       64.0
...            ...          ...            ...        ...        ...
145395    Illinois          USA  United States        NaN        NaN
145398   Minnesota          USA  United States        NaN        NaN
145405      Alaska          USA  United States        NaN        NaN
145418   Minnesota          USA  United States        NaN        NaN
145427     Georgia          USA  United States        NaN        NaN

         died_date
5              NaN
10      1932-11-18
17             NaN
35             NaN
40             NaN
...            ...
145395         NaN
145398         NaN
145405         NaN
145418         NaN
145427         NaN

[12968 rows x 10 columns]

In [443]:
# find athletes with names that contain exactly two vowels
bios[bios['name'].str.contains(r'^[^AEIOUaeiou]*[AEIOUaeiou][^AEIOUaeiou]*[AEIOUaeiou][^AEIOUaeiou]*$', na = False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
12,13,J. Defert,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
30,31,André Prévost,1875-02-28,Paris VIIIe,Paris,FRA,France,NaN,NaN,1951-11-22
68,69,Sam Smith,1971-11-27,Epping,England,GBR,Great Britain,175.0,62.0,NaN
70,71,Ruth Winch,1870-08-25,Ryde,England,GBR,Great Britain,NaN,NaN,1952-01-09
73,74,Sky Andrew,1962-03-31,Newham,England,GBR,Great Britain,185.0,78.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145340,149062,A. J. Hurt,2000-12-05,Truckee,California,USA,United States,NaN,NaN,NaN
145349,149072,Kris Horn,1994-04-25,Weymouth,Massachusetts,USA,United States,NaN,NaN,NaN
145382,149105,Dylan Walczyk,1993-06-25,Rochester,New York,USA,United States,NaN,NaN,NaN
145452,149177,Radek Rýdl,2001-07-15,Jilemnice,Liberecký kraj,CZE,Czechia,NaN,NaN,NaN
145483,149210,Feng He,2004-03-31,NaN,NaN,NaN,People's Republic of China,NaN,NaN,NaN

In [444]:
# find athletes with names that have repeates consecutive letters
bios[bios['name'].str.contains(r'(.)\1', na = False)]

/tmp/ipykernel_1291/4186997929.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  bios[bios['name'].str.contains(r'(.)\1', na = False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27
13,14,Étienne Durand,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
17,18,Jean-Philippe Gatien,1968-10-16,Alès,Gard,FRA,France,178.0,73.0,NaN
20,21,Pierre Hirsch,1900-11-08,Paris Ie,Paris,FRA,France,NaN,NaN,1942-04-19
28,29,Albert Lippmann,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
145474,149201,Nadine Hofstetter,1994-10-21,Romoos,Luzern,SUI,Switzerland,164.0,68.0,NaN
145488,149215,Shakeel John,2001-07-30,Mount Hope,Tunapuna-Piarco,TTO,Trinidad and Tobago,NaN,NaN,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [445]:
# find athletes with names ending in 'son'
bios[bios['name'].str.contains(r'son$',case=False, na = False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
37,38,Helen Aitchison,1881-12-06,Sunderland,England,GBR,Great Britain,NaN,NaN,1947-05-26
92,93,Anne Gibson,1968-10-26,Dumfries,Scotland,GBR,Great Britain,173.0,70.0,NaN
113,114,Julian Robertson,1969-10-09,Peterborough,England,GBR,Great Britain,182.0,73.0,NaN
120,121,Chris Wilkinson,1970-01-05,Southampton,England,GBR,Great Britain,180.0,72.0,NaN
373,374,Don Jackson,1932-10-25,Lindsay,Ontario,CAN,Canada,178.0,NaN,2009-01-26
...,...,...,...,...,...,...,...,...,...,...
145419,149142,Jake Sanderson,2002-07-08,Whitefish,Montana,USA,United States,NaN,NaN,NaN
145424,149147,Jonathan Gustafson,1997-03-05,Massena,New York,USA,United States,NaN,NaN,NaN
145441,149164,Casey Dawson,2000-08-02,Park City,Utah,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145461,149188,Kent Johnson,2002-10-18,Port Moody,British Columbia,CAN,Canada,185.0,75.0,NaN

In [446]:
# find athlets born in a year starting ending with 8
bios[bios['born_date'].str.contains(r'8$', na = False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
20,21,Pierre Hirsch,1900-11-08,Paris Ie,Paris,FRA,France,NaN,NaN,1942-04-19
30,31,André Prévost,1875-02-28,Paris VIIIe,Paris,FRA,France,NaN,NaN,1951-11-22
51,52,Edith Hannam,1878-11-28,Bristol,England,GBR,Great Britain,NaN,NaN,1951-01-16
52,53,Dorothy Holman,1883-07-18,Kilburn,England,GBR,Great Britain,NaN,NaN,1968-06-15
71,72,Clare Wood,1968-03-08,Zululand,KwaZulu-Natal,RSA,Great Britain,175.0,65.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145461,149188,Kent Johnson,2002-10-18,Port Moody,British Columbia,CAN,Canada,185.0,75.0,NaN
145466,149193,Mikkel Aagaard,1995-10-18,Frederikshavn,Nordjylland,DEN,Denmark,184.0,81.0,NaN
145467,149194,Elisa Nakab,1998-05-08,Briançon,Hautes-Alpes,FRA,Italy,NaN,NaN,NaN
145480,149207,Gao Yuhao,2000-06-18,NaN,NaN,NaN,People's Republic of China,NaN,NaN,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN

In [447]:
bios[bios['born_country'].isin(['USA','FRA'])]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145467,149194,Elisa Nakab,1998-05-08,Briançon,Hautes-Alpes,FRA,Italy,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

In [448]:
bios[bios['born_country'].isin(['USA','FRA']) & (bios['name'].str.startswith('Keith'))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN

In [449]:
bios.query('born_country == "USA"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145445,149168,Kristen Santos,1994-11-02,Fairfield,Connecticut,USA,United States,NaN,NaN,NaN
145446,149169,Corinne Stoddard,2001-08-15,Seattle,Washington,USA,United States,NaN,NaN,NaN
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN

In [450]:
bios.query('born_country == "USA" & born_city == "Burlingame"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
2719,2731,Diana Gee,1968-12-21,Burlingame,California,USA,United States,162.0,45.0,NaN
40145,40453,Catriona Fallon,1970-08-08,Burlingame,California,USA,United States,185.0,77.0,NaN
77768,78359,Ben Eastman,1911-07-09,Burlingame,California,USA,United States,185.0,70.0,2002-10-06
87182,87878,Duncan Kennedy,1967-12-20,Burlingame,California,USA,United States,180.0,77.0,NaN
107963,109104,Chloe Kloezeman,1986-05-29,Burlingame,California,USA,Greece,167.0,61.0,NaN

In [451]:
bios_new = bios.copy()

In [452]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

In [453]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

In [454]:
bios_new.query('first_name == "Keith"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith

In [455]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
 10  first_name    145500 non-null  object
dtypes: float64(2), int64(1), object(8)
memory usage: 12.2+ MB

In [456]:
bios_new['born_datetime'] = pd.to_datetime(bios['born_date'])

In [457]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15

In [458]:
bios_new.groupby(bios_new['born_datetime'].dt.year).count()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime
born_datetime,,,,,,,,,,,,
1828.0,1,1,1,1,1,1,1,0,0,1,1,1
1831.0,2,2,2,2,2,2,2,0,0,2,2,2
1833.0,1,1,1,1,1,1,1,0,0,1,1,1
1836.0,1,1,1,1,1,1,1,0,0,1,1,1
1837.0,1,1,1,1,1,1,1,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2005.0,163,163,163,64,64,64,163,13,12,1,163,163
2006.0,17,17,17,8,8,8,17,1,0,0,17,17
2007.0,3,3,3,1,1,1,3,0,0,0,3,3
2008.0,3,3,3,2,2,2,3,1,1,0,3,3
2009.0,1,1,1,1,1,1,1,0,0,0,1,1

In [459]:
bios_new.groupby(bios_new['born_datetime'].dt.year)['name'].count().reset_index().sort_values('name', ascending=False)

     born_datetime  name
139         1972.0  2231
152         1985.0  2227
140         1973.0  2216
138         1971.0  2205
137         1970.0  2174
..             ...   ...
4           1837.0     1
2           1833.0     1
6           1839.0     1
12          1845.0     1
176         2009.0     1

[177 rows x 2 columns]

In [460]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  object
 2   born_date      143693 non-null  object
 3   born_city      110908 non-null  object
 4   born_region    110908 non-null  object
 5   born_country   110908 non-null  object
 6   NOC            145499 non-null  object
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   object
 10  first_name     145500 non-null  object
 11  born_datetime  143693 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 13.3+ MB

In [461]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year
bios_new[['name' , 'born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [462]:
bios_new['height_category'] = bios['height_cm'].apply(lambda x: 'short' if x < 165 else ('average' if x < 185 else 'tall') )
bios_new .head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,tall

In [463]:
def categorize_athlete(row):
  if row['height_cm'] < 175 and row['weight_kg'] < 70:
    return 'Lightweight'
  elif row['height_cm'] < 185 or row['weight_kg'] <= 80:
    return 'Middleweight'
  else:
    return 'Heavyweight'
bios_new['category'] = bios.apply(categorize_athlete, axis = 1)
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,height_category,category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,average,Lightweight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,tall,Heavyweight

In [464]:
bios['height_rank'] = bios['height_cm'].rank(ascending =False)
bios.sort_values(['height_rank'])

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
89070,89782,Yao Ming,1980-09-12,Xuhui District,Shanghai,CHN,People's Republic of China,226.0,141.0,NaN,1.0
6978,7013,Arvydas Sabonis,1964-12-19,Kaunas,Kaunas,LTU,Lithuania Soviet Union,223.0,122.0,NaN,2.5
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN,2.5
5673,5696,Gunther Behnke,1963-01-19,Leverkusen,Nordrhein-Westfalen,GER,Germany,221.0,114.0,NaN,5.0
89075,89787,Roberto Dueñas,1975-11-01,Madrid,Madrid,ESP,Spain,221.0,137.0,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...
145490,149217,Sin Ye-Chan,1995-06-13,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN,NaN
145491,149218,Matthew Wepke,1989-12-05,NaN,NaN,NaN,Jamaica,NaN,NaN,NaN,NaN
145492,149219,Carlos García-Ordóñez,1927-04-24,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,NaN,NaN,2019-11-24,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,NaN

In [465]:
bios.sort_values(['height_rank']).sample(10)[['name','height_rank']]

                       name  height_rank
6319      Edward Jurkiewicz       3949.5
72754         Hamadi Haddou      83975.0
124500         Natalie Dell      58380.5
89411       Alesia Bakunova      54014.0
25767         Eli Leventhal      46966.0
72983         Carlos Monges      38677.0
106407     Chuang Chih-Yuan      89274.5
16956          Emilio Vidal     100785.0
122265  Concepción Bellorin     104776.0
108137  Vasileios Kournetas       6946.0

In [466]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [467]:
bios_new = pd.merge(bios, nocs, left_on  ='born_country', right_on='NOC', how= 'left')
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_rank,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,27597.5,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,27597.5,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,83975.0,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,NaN,GBR,UK,NaN

In [468]:
bios_new.rename(columns={'region':'born_country_full'}, inplace=True)
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_rank,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,27597.5,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,27597.5,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,83975.0,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,NaN,GBR,UK,NaN

In [469]:
bios_new[bios_new['NOC_x'] != bios_new['born_country_full']][['name','NOC_x','born_country_full']]

                       name    NOC_x born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

In [470]:
usa = bios[bios['born_country'] == 'USA'].copy()
gbr = bios[bios['born_country'] == 'GBR'].copy()

In [471]:
usa.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,51063.0
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,77037.5
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,100785.0
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,NaN
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,83975.0

In [472]:
gbr.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,NaN
37,38,Helen Aitchison,1881-12-06,Sunderland,England,GBR,Great Britain,NaN,NaN,1947-05-26,NaN
38,39,Geraldine Beamish,1883-06-23,Forest Gate,England,GBR,Great Britain,NaN,NaN,1972-05-10,NaN
39,40,Dora Boothby,1881-08-02,Finchley,England,GBR,Great Britain,NaN,NaN,1970-02-22,NaN
40,41,Julie Bradbury,1967-02-12,Oxford,England,GBR,Great Britain,175.0,64.0,NaN,58380.5

In [473]:
new_df = pd.concat([usa,gbr])

In [474]:
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN,51063.0
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN,77037.5
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN,100785.0
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20,NaN
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN,83975.0

In [475]:
new_df.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,NaN
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,NaN
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN,24214.0
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,NaN
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,NaN

In [476]:
bios['born_city'].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Kirovgrad             1
Pereiaslav            1
Podgornyy             1
Kudepsta              1
Furmanov              1
Name: count, Length: 22368, dtype: int64

In [477]:
bios[bios['born_country'] == 'USA']['born_region'].value_counts().head(15)

born_region
California       1634
New York          990
Illinois          585
Massachusetts     530
Pennsylvania      530
New Jersey        381
Texas             368
Minnesota         365
Ohio              328
Michigan          319
Washington        240
Florida           235
Wisconsin         209
Colorado          207
Connecticut       156
Name: count, dtype: int64

In [478]:
bios[bios['born_country'] == 'USA']['born_region'].value_counts().tail(10)

born_region
Alaska           45
Arkansas         42
Idaho            41
New Mexico       38
Nevada           36
South Dakota     27
West Virginia    24
Delaware         22
North Dakota     16
Wyoming          14
Name: count, dtype: int64

In [479]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [480]:
combined_df = pd.merge(results, bios, on ='athlete_id', how='left')
combined_df

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,...,Marián Skupek,2001-07-12,Gelnica,Košice,SVK,Slovakia,196.0,108.0,NaN,3170.5
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,...,Elsa Fermbäck,1998-03-28,Vemdalen,Jämtland,SWE,Sweden,NaN,NaN,NaN,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,...,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,...,Hilma Lövblom,2000-08-16,Täby,Stockholm,SWE,Sweden,NaN,NaN,NaN,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,...,Charlotta Säfvenberg,1994-10-07,Kungsbacka,Halland,SWE,Sweden,NaN,NaN,NaN,NaN

In [481]:
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_rank
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN